# .github/workflows/build.yml
name: Build and Release Subconverter Desktop

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Get latest subconverter release info
      id: get_subconverter_release
      run: |
        $response = Invoke-RestMethod -Uri "https://api.github.com/repos/metacubex/subconverter/releases/latest" -Headers @{Authorization = "token ${{ secrets.GITHUB_TOKEN }}"}
        $latest_tag = $response.tag_name
        
        # تغییر در اینجا: به دنبال فایل با پسوند .7z می‌گردیم
        $asset_url = $response.assets | Where-Object { $_.name -like "*windows-amd64*.7z" } | Select-Object -ExpandProperty browser_download_url
        
        echo "LATEST_SUB_TAG=$latest_tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "SUB_ASSET_URL=$asset_url" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell

    - name: Download and Extract subconverter.exe
      run: |
        if ("${{ env.SUB_ASSET_URL }}" -eq "") {
          Write-Error "Could not find subconverter Windows AMD64 .7z asset URL."
          exit 1
        }
        # دانلود فایل .7z
        Invoke-WebRequest -Uri "${{ env.SUB_ASSET_URL }}" -OutFile "subconverter_release.7z"
        
        # برای استخراج فایل .7z نیاز به 7-Zip دارید.
        # GitHub Actions runnerها معمولاً 7-Zip را از قبل نصب دارند.
        # از دستور 7z برای استخراج استفاده می‌کنیم.
        & "C:\Program Files\7-Zip\7z.exe" x "subconverter_release.7z" -o*
        
        # پیدا کردن فایل subconverter.exe پس از استخراج
        # ممکن است در یک پوشه فرعی باشد، پس به صورت بازگشتی جستجو می‌کنیم
        $subconverterExe = Get-ChildItem -Path . -Recurse -Filter "subconverter.exe" | Select-Object -First 1
        
        if ($subconverterExe) {
          # اگر فایل اجرایی در روت نبود، آن را به روت منتقل می‌کنیم
          if ($subconverterExe.DirectoryName -ne (Get-Location).Path) {
            Move-Item -Path $subconverterExe.FullName -Destination "subconverter.exe" -Force
          }
        } else {
          Write-Error "subconverter.exe not found after extracting .7z archive. Please check the archive content."
          exit 1
        }
        
        # حذف فایل .7z دانلود شده و هر پوشه استخراج شده
        Remove-Item -Force "subconverter_release.7z"
        Get-ChildItem -Path . -Directory -Filter "subconverter-windows-amd64-*" | Remove-Item -Recurse -Force
      shell: powershell

    - name: Install dependencies
      run: npm install

    - name: Build Electron application for Windows
      run: npm run build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: subconverter-desktop-${{ env.LATEST_SUB_TAG }}-${{ github.run_number }}
        release_name: Subconverter Desktop with ${{ env.LATEST_SUB_TAG }} (Build ${{ github.run_number }})
        body: |
          این یک بیلد خودکار از برنامه دسکتاپ Subconverter است که شامل موتور تبدیل Subconverter نسخه ${{ env.LATEST_SUB_TAG }} می‌باشد.
          این Release هر سه روز یک بار به‌روزرسانی می‌شود.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/Subconverter Desktop-1.0.0-win.zip
        asset_name: Subconverter_Desktop_Win-${{ env.LATEST_SUB_TAG }}.zip
        asset_content_type: application/zip
